name: Buildem
on:
  push:
    branches: [ main ]

jobs:
  build-all-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16

    # ANDY - old technique using yarn
    # - name: install dependencies
    #   run: yarn install
    # - name: publish
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: yarn electron:build

    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        github_token: ${{ secrets.github_token }}
        
        # Hopefully this solves all my problems!  Yes it does. 🎉  See https://github.com/samuelmeuli/action-electron-builder/issues/66
        # It causes this invocation
        # $ /Users/runner/work/vue-electron-builder1/vue-electron-builder1/node_modules/.bin/vue-cli-service electron:build --mac
        # instead of the problematic
        # $ /Users/runner/work/vue-electron-builder1/vue-electron-builder1/node_modules/.bin/electron-builder --mac
        # which in retrospect makes sense since we are using VUE with electron, not using plain electron.  
        # Cos this samuelmeuli/action-electron-builder@v1 plugin is all about ELECTRON, not specifically VUE.  Though it is nice 
        # enough to give us this special VUE option.
        use_vue_cli: true

        # The publish key contains a set of options instructing electron-builder on how it should publish artifacts and build update info files for auto update.
        # Plugin OFFICIAL docs https://github.com/samuelmeuli/action-electron-builder say 'args:' is for
        #   Other arguments to pass to the electron-builder command, e.g. configuration overrides
        # OFFICIAL https://www.electron.build/configuration/publish.html doco says: CLI Usage of electron-builder command 
        # --publish, -p  [choices: "onTag", "onTagOrDraft", "always", "never"]
        args: "-p always"

        # If the commit is tagged with a version (e.g. "v1.0.0"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}

        # ANDY 
        # if: runner.os=='linux'
        #   run: |
        #     ls -l
        #     echo "hi there"
        # Need to work out all this syntax and options passing...
        #   with:
        #     args: |
        #       target: deb

    - name: ANDY View resulting directory structure
      shell: bash
      run: |
        ls -l
        # ls -l dist_electron/  - doesn't exist only dist/ exists
        ls -l dist/
        # ls -lR  - too much output

    # - name: ANDY Save generated file as an artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     # The act of downloading zips up the artifact and adds the .zip to the downloaded file
    #     name: vue-electron-builder1-${{ matrix.os }}  # to
    #     path: dist_electron/  # from, though this is the whole directory - a bit much

